version: '2'

services:
  intalgo-dbt:
    container_name: intalgo-dbt
    build:
      context: .
      dockerfile: dbt.Dockerfile 
    environment: 
      - INTALGO_DBT_CONTAINER=${INTALGO_DBT_CONTAINER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}

  intalgo-web:
    container_name: intalgo-web
    build:
      context: .
      dockerfile: flask.Dockerfile 
    ports:
      - "80:80"
    restart: "unless-stopped"
    volumes:
      - ./data:/data 
      - ./src/dbt/:/intalgo/src/dbt
      - ./src/flask/:/intalgo/src/flask
      - "//var/run/docker.sock:/var/run/docker.sock"
    environment: 
      - INTALGO_DBT_CONTAINER=${INTALGO_DBT_CONTAINER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}

